### PR TITLE
Update icons

### LINKED ISSUE #388: Rename Mergin -> Mergin Maps
Search for occurrences of `Mergin` in const strings and replace them with `Mergin Maps`. Also `Input` -> `Mergin Maps Input`

### PR DESCRIPTION
**Pull request by alexbruy**
More work on rebranding:

- replace logo+text icon with simple logo icon
- remove status actions as it now merged with sync action
- use new icons from Tabler icon set
- replace Mergin → Mergin Maps and Input → Mergin Maps Input (fix #388)

Toolbar
зображення
Browser
зображення
Sync dialog
зображення
Local and server project context menus
зображення

### CODE REVIEW

**Comment by PeterPetrik** [comment]
user has a prroblem 

```
warning:/Users/myusername/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Mergin/plugin.py:120: DeprecationWarning: an integer is required (got type float). Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
              layout.addSpacing(self.toolbar.iconSize().width() / 2)
```

on macOS. Can you please check the line `Mergin/plugin.py:120` and potentially fix it here too?

**Review by PeterPetrik — APPROVED** [review]
looks good!

**Comment by tomasMizera** [comment]
> user has a prroblem
> 
> ```
> warning:/Users/myusername/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Mergin/plugin.py:120: DeprecationWarning: an integer is required (got type float). Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
>               layout.addSpacing(self.toolbar.iconSize().width() / 2)
> ```
> 
> on macOS. Can you please check the line `Mergin/plugin.py:120` and potentially fix it here too?

@PeterPetrik Alex @alexbruy removed that part of the code so it should be addressed

**Review by tomasMizera — APPROVED** [review]
Looks really good! Let's replace the download icon with three dots and then we can merge this.

**Comment by alexbruy** [comment]
> user has a prroblem

This is just a deprecation warning from Python, there are tons of the similar warnings in QGIS. Moreover this is related to the part of code which is already removed.

**Comment by alexbruy** [comment]
As discussed with @tomasMizera download icon replaced with 3 dots icon
зображення

**Pull request merged**
